apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aqsa2106/Nodejs.git'  # Ganti dengan URL repo kamu
    targetRevision: main
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # Ganti dengan namespace yang sesuai jika berbeda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
