apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: statefulset-reader
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-statefulsets
  namespace: default
subjects:
- kind: ServiceAccount
  name: dashboard-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: statefulset-reader
  apiGroup: rbac.authorization.k8s.io
